### ISSUE TITLE
GUI crashes upon manual STRRJ angle entry of 95 deg

### ISSUE THREAD

**Issue by juggler2000** [ISS-Mimic/Mimic#185] opened 2020-10-10 17:13 UTC
Unsure if it was specifically caused by the 95 amt, but GUI crashed up on entering 95 deg for STRRJ on Manual screen via number pad.

**Comment by Digisembler** [comment] 2021-07-21 21:36
duplicate of #210, closing this one since the other one has the error message

**Closed by Digisembler** 2021-07-21 21:36 UTC
Labels: Bug, GUI
