### ISSUE TITLE
Fix dedent import issue

### ISSUE THREAD

**Issue by dallasbrittany** [ISS-Mimic/Mimic#209] opened 2020-12-12 21:10 UTC
I haven't figured out how to reliably reproduce the issue, but there seems to be a problem with importing dedent from matplotlib.cbook. This package affects the night regions being drawn on the screen. This link might be helpful: https://github.com/matplotlib/basemap/issues/494

![screenshot](https://user-images.githubusercontent.com/4213800/101994948-ec72cf80-3c8b-11eb-956a-7793dfc8b97b.jpg)

**Comment by Digisembler** [comment] 2021-07-28 21:57
can't reproduce error, keep issue open for now

**Comment by ISS-Mimic** [comment] 2022-01-21 02:49
closing for now, haven't seen in a while

**Closed by ISS-Mimic** 2022-01-21 02:49 UTC
